//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://mavenproject2.mycompany.com/", ConfigurationName="ServiceReference2.Nombre")]
    public interface Nombre {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento return del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://mavenproject2.mycompany.com/Nombre/DevuelveNombreRequest", ReplyAction="http://mavenproject2.mycompany.com/Nombre/DevuelveNombreResponse")]
        $safeprojectname$.ServiceReference2.DevuelveNombreResponse DevuelveNombre($safeprojectname$.ServiceReference2.DevuelveNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://mavenproject2.mycompany.com/Nombre/DevuelveNombreRequest", ReplyAction="http://mavenproject2.mycompany.com/Nombre/DevuelveNombreResponse")]
        System.Threading.Tasks.Task<$safeprojectname$.ServiceReference2.DevuelveNombreResponse> DevuelveNombreAsync($safeprojectname$.ServiceReference2.DevuelveNombreRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevuelveNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevuelveNombre", Namespace="http://mavenproject2.mycompany.com/", Order=0)]
        public $safeprojectname$.ServiceReference2.DevuelveNombreRequestBody Body;
        
        public DevuelveNombreRequest() {
        }
        
        public DevuelveNombreRequest($safeprojectname$.ServiceReference2.DevuelveNombreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DevuelveNombreRequestBody {
        
        public DevuelveNombreRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevuelveNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevuelveNombreResponse", Namespace="http://mavenproject2.mycompany.com/", Order=0)]
        public $safeprojectname$.ServiceReference2.DevuelveNombreResponseBody Body;
        
        public DevuelveNombreResponse() {
        }
        
        public DevuelveNombreResponse($safeprojectname$.ServiceReference2.DevuelveNombreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class DevuelveNombreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public DevuelveNombreResponseBody() {
        }
        
        public DevuelveNombreResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NombreChannel : $safeprojectname$.ServiceReference2.Nombre, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NombreClient : System.ServiceModel.ClientBase<$safeprojectname$.ServiceReference2.Nombre>, $safeprojectname$.ServiceReference2.Nombre {
        
        public NombreClient() {
        }
        
        public NombreClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NombreClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NombreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NombreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        $safeprojectname$.ServiceReference2.DevuelveNombreResponse $safeprojectname$.ServiceReference2.Nombre.DevuelveNombre($safeprojectname$.ServiceReference2.DevuelveNombreRequest request) {
            return base.Channel.DevuelveNombre(request);
        }
        
        public string DevuelveNombre() {
            $safeprojectname$.ServiceReference2.DevuelveNombreRequest inValue = new $safeprojectname$.ServiceReference2.DevuelveNombreRequest();
            inValue.Body = new $safeprojectname$.ServiceReference2.DevuelveNombreRequestBody();
            $safeprojectname$.ServiceReference2.DevuelveNombreResponse retVal = (($safeprojectname$.ServiceReference2.Nombre)(this)).DevuelveNombre(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<$safeprojectname$.ServiceReference2.DevuelveNombreResponse> $safeprojectname$.ServiceReference2.Nombre.DevuelveNombreAsync($safeprojectname$.ServiceReference2.DevuelveNombreRequest request) {
            return base.Channel.DevuelveNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<$safeprojectname$.ServiceReference2.DevuelveNombreResponse> DevuelveNombreAsync() {
            $safeprojectname$.ServiceReference2.DevuelveNombreRequest inValue = new $safeprojectname$.ServiceReference2.DevuelveNombreRequest();
            inValue.Body = new $safeprojectname$.ServiceReference2.DevuelveNombreRequestBody();
            return (($safeprojectname$.ServiceReference2.Nombre)(this)).DevuelveNombreAsync(inValue);
        }
    }
}
