//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace $safeprojectname$.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento HelloWorldResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        $safeprojectname$.ServiceReference1.HelloWorldResponse HelloWorld($safeprojectname$.ServiceReference1.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<$safeprojectname$.ServiceReference1.HelloWorldResponse> HelloWorldAsync($safeprojectname$.ServiceReference1.HelloWorldRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DevuelveNombreResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevuelveNombre", ReplyAction="*")]
        $safeprojectname$.ServiceReference1.DevuelveNombreResponse DevuelveNombre($safeprojectname$.ServiceReference1.DevuelveNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DevuelveNombre", ReplyAction="*")]
        System.Threading.Tasks.Task<$safeprojectname$.ServiceReference1.DevuelveNombreResponse> DevuelveNombreAsync($safeprojectname$.ServiceReference1.DevuelveNombreRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public $safeprojectname$.ServiceReference1.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest($safeprojectname$.ServiceReference1.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public $safeprojectname$.ServiceReference1.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse($safeprojectname$.ServiceReference1.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevuelveNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevuelveNombre", Namespace="http://tempuri.org/", Order=0)]
        public $safeprojectname$.ServiceReference1.DevuelveNombreRequestBody Body;
        
        public DevuelveNombreRequest() {
        }
        
        public DevuelveNombreRequest($safeprojectname$.ServiceReference1.DevuelveNombreRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DevuelveNombreRequestBody {
        
        public DevuelveNombreRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DevuelveNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DevuelveNombreResponse", Namespace="http://tempuri.org/", Order=0)]
        public $safeprojectname$.ServiceReference1.DevuelveNombreResponseBody Body;
        
        public DevuelveNombreResponse() {
        }
        
        public DevuelveNombreResponse($safeprojectname$.ServiceReference1.DevuelveNombreResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DevuelveNombreResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DevuelveNombreResult;
        
        public DevuelveNombreResponseBody() {
        }
        
        public DevuelveNombreResponseBody(string DevuelveNombreResult) {
            this.DevuelveNombreResult = DevuelveNombreResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : $safeprojectname$.ServiceReference1.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<$safeprojectname$.ServiceReference1.WebServiceSoap>, $safeprojectname$.ServiceReference1.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        $safeprojectname$.ServiceReference1.HelloWorldResponse $safeprojectname$.ServiceReference1.WebServiceSoap.HelloWorld($safeprojectname$.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            $safeprojectname$.ServiceReference1.HelloWorldRequest inValue = new $safeprojectname$.ServiceReference1.HelloWorldRequest();
            inValue.Body = new $safeprojectname$.ServiceReference1.HelloWorldRequestBody();
            $safeprojectname$.ServiceReference1.HelloWorldResponse retVal = (($safeprojectname$.ServiceReference1.WebServiceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<$safeprojectname$.ServiceReference1.HelloWorldResponse> $safeprojectname$.ServiceReference1.WebServiceSoap.HelloWorldAsync($safeprojectname$.ServiceReference1.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<$safeprojectname$.ServiceReference1.HelloWorldResponse> HelloWorldAsync() {
            $safeprojectname$.ServiceReference1.HelloWorldRequest inValue = new $safeprojectname$.ServiceReference1.HelloWorldRequest();
            inValue.Body = new $safeprojectname$.ServiceReference1.HelloWorldRequestBody();
            return (($safeprojectname$.ServiceReference1.WebServiceSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        $safeprojectname$.ServiceReference1.DevuelveNombreResponse $safeprojectname$.ServiceReference1.WebServiceSoap.DevuelveNombre($safeprojectname$.ServiceReference1.DevuelveNombreRequest request) {
            return base.Channel.DevuelveNombre(request);
        }
        
        public string DevuelveNombre() {
            $safeprojectname$.ServiceReference1.DevuelveNombreRequest inValue = new $safeprojectname$.ServiceReference1.DevuelveNombreRequest();
            inValue.Body = new $safeprojectname$.ServiceReference1.DevuelveNombreRequestBody();
            $safeprojectname$.ServiceReference1.DevuelveNombreResponse retVal = (($safeprojectname$.ServiceReference1.WebServiceSoap)(this)).DevuelveNombre(inValue);
            return retVal.Body.DevuelveNombreResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<$safeprojectname$.ServiceReference1.DevuelveNombreResponse> $safeprojectname$.ServiceReference1.WebServiceSoap.DevuelveNombreAsync($safeprojectname$.ServiceReference1.DevuelveNombreRequest request) {
            return base.Channel.DevuelveNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<$safeprojectname$.ServiceReference1.DevuelveNombreResponse> DevuelveNombreAsync() {
            $safeprojectname$.ServiceReference1.DevuelveNombreRequest inValue = new $safeprojectname$.ServiceReference1.DevuelveNombreRequest();
            inValue.Body = new $safeprojectname$.ServiceReference1.DevuelveNombreRequestBody();
            return (($safeprojectname$.ServiceReference1.WebServiceSoap)(this)).DevuelveNombreAsync(inValue);
        }
    }
}
